Azure/doAzureParallel

- R/doAzureParallel.R
- tests/testthat/test-integration.R
Fixed correctly merge tasks that have chunkSize parameter assigned
> Added chunksize integration test

- R/cluster.R
- R/doAzureParallel.R
- R/helpers.R
- R/utility.R
- Added setup methods for pool, task, and job for specific doAzureParallel job
- Clean up sas token expiration dates
> Moving rAzureBatch logic to doAzureParallel

- DESCRIPTION
- R/cluster.R
- R/utility.R
- changed command line from R to Rscript to enable usage of args
- updated how packages were being installed on add pool
> Changed R installation command line

- samples/sas_resource_files_example.R
- Added proper namespace packages
- Use correct parameters
https://github.com/Azure/doAzureParallel/issues/24
> Fixed SAS resource file samples

- R/utility.R
> Added validation for quota limits and bad getPool requests in waitForNodesToComplete

- docs/21-distributing-data.md
- samples/resource_files/resource_files_example.R
Ref: 
https://github.com/Azure/doAzureParallel/issues/82
> Updating documentation for default container permission settings

- DESCRIPTION
- R/cluster.R
- R/utility.R
> Check if existing pool is deleted when makeCluster is called

- tests/testthat/test-lint.R
- tests/testthat/test-live.R
Users do not have to run their own simple test scenario
> Added live scenario test

- R/doAzureParallel.R
- R/utility.R
- inst/startup/install_cran.R
https://github.com/Azure/doAzureParallel/issues/96
> Wait for job preparation task function

- R/doAzureParallel.R
- R/helpers.R
> Fixed job creation

- inst/startup/merger.R
- tests/testthat/test-live.R
> Fix: Do not use task chunk size during cloud combine function

- .lintr
- R/cluster.R
- R/doAzureParallel.R
- R/validationUtilities.R
- tests/testthat/test-cluster-config.R
- tests/testthat/test-live.R
- tests/testthat/test-long-running-job.R
- tests/testthat/test-package-installation-bioc.R
- tests/testthat/test-package-installation-github.R
Iterator args was reading both bioconductor and github objects. It should be ignored.
> Fix: Bioconductor and Github packages installation

- R/jobUtilities.R
- Added precise percentage
- Added message of (number of completed tasks / total tasks)
- Added message about merge task being run
**Started Job:**
Job Summary: 
Id: job20171204213612
Waiting for tasks to complete. . .
|                                                                                                         | 0.00% (0/5) 
**Finished Job:**
Job Summary: 
Id: job20171204213033
Waiting for tasks to complete. . .
|=========================================================================================================| 100.00% (5/5)  Tasks have completed. Merging results
Number of errors: 0
> Implemented progress bar with verbose details

- R/jobUtilities.R
- R/stringUtilities.R
Job Summary: 
Id: job20171206015806
Waiting for tasks to complete. . .
| Progress: 100.00% (4/4) | Running: 0 | Queue: 0 | Completed: 4 | Failed: 0 |
Tasks have completed. Merging results
Number of errors: 0
> Changing UI of progress bar

- R/jobUtilities.R
- Typo on Queued
- Running Tasks was counting the merge task
> Progress Bar

- R/doAzureParallel.R
- R/jobUtilities.R
- R/storage_management.R
- R/stringUtilities.R
- Adding tasks will update every time a new task is added in Batch.
- Details about the job submission
> Improve R console UI experience

- R/cluster.R
> Fixed order of package installation

- R/cluster.R
- R/doAzureParallel.R
- R/helpers.R
- inst/startup/cluster_setup.sh
- This is a breaking change for users that are reusing their pools before this version change
> Bundling worker scripts into zip

- R/doAzureParallel.R
- R/helpers.R
Removed dependency for zip package installation
> Revert changes from node scripts

- R/cluster.R
- R/utility.R
parse and display server side error for add pool
> improve error handling for create cluster

- R/credentials.R
> Fixed incorrect variable name

- samples/caret/caret_example.R
Parameter name looks to have changed. Fixing. There are still some issues that I will open a separate ticket for.
> Fixing change of named parameter in makeCluster

- R/doAzureParallel.R
- R/jobUtilities.R
Submitting tasks (32/32)
Job Preparation Status: Package(s) being installed
Waiting for tasks to complete. . .
| Progress: 100.00% (32/32) | Running: 0 | Queued: 0 | Completed: 32 | Failed: 0 |
Tasks have completed.
> Fixed output for job submission

- inst/startup/worker.R
> Fixed package strip name

- docs/72-persistent-storage.md
> Fix: Updating Persistent Storage Documentation 

- CHANGELOG.md
- DESCRIPTION
- Update CHANGELOG
- Ramped up package version
> v0.7.1 Release

- docs/52-azure-foreach-options.md
Fix - Incorrect arguments for enabling merge task
> Fix Azure Foreach Options

- R/file-operations.R
- docs/40-clusters.md
> Fix: Get Cluster File - Full Path

- R/cluster.R
- README.md
- docs/02-getting-started-script.md
- docs/04-azure-requirements.md
- docs/40-clusters.md
> Fix: Documentation typos and fixes

- inst/startup/install_github.R
- inst/startup/worker.R
#301 
Add ability to install github packages by reference:
``` R
foreach(i = 1:3, github = c("Azure/rAzureBatch@v0.6.0")) %dopar% { "rAzureBatch" %in% (.packages())}
```
> Feature: Added github branch installation

- CHANGELOG.md
- DESCRIPTION
* Fix: Documentation typos and fixes (#307) ([1d26dd8](https://github.com/Azure/doAzureParallel/commit/1d26dd8)), closes [#307](https://github.com/Azure/doAzureParallel/issues/307)
* Fix: File share sample (#312) ([96081cc](https://github.com/Azure/doAzureParallel/commit/96081cc)), closes [#312](https://github.com/Azure/doAzureParallel/issues/312)
* Added 0.7.1 changelog version (#286) ([ad7acf1](https://github.com/Azure/doAzureParallel/commit/ad7acf1)), closes [#286](https://github.com/Azure/doAzureParallel/issues/286)
* Added docs (#298) ([b9ffe3e](https://github.com/Azure/doAzureParallel/commit/b9ffe3e)), closes [#298](https://github.com/Azure/doAzureParallel/issues/298)
* Added github branch installation (#302) ([4020a93](https://github.com/Azure/doAzureParallel/commit/4020a93)), …
> Release: v0.7.2

- R/autoscale.R
- docs/32-autoscale.md
> Feature: Added Queue/Running Autoscale Formula

- inst/startup/cluster_setup.sh
> Fix: Revert Cluster Setup File

- R/autoscale.R
1) Incorrect documentation 
2) Change the pool ids for the get cluster function inside resize cluster
> Fix: Resize Cluster 
